"use client";
import Image from "next/image";
import Link from "next/link";
import { useMemo, useState, type PointerEvent as ReactPointerEvent } from "react";
import type { EntityRelation, Institution, Resource, Topic } from "@/types";
import { getKnowledgeRole, knowledgeRoleZh, resourceTypeZh } from "@/lib/display";
import { atlasInquiries } from "@/lib/atlas/contentModel";
import { curatedStories } from "@/lib/atlas/curatedStories";
import { curatedAuthorizationDrafts } from "@/lib/atlas/curatedRelations";

type Props={topics:Topic[];resources:Resource[];institutions:Institution[];relations:EntityRelation[]};
type Surface="index"|"journey"|"compare"; type Lens="story"|"relations";

export function ArchiveKnowledgeRoom({topics,resources,institutions,relations}:Props){
 const sortedTopics=useMemo(()=>[...topics].sort((a,b)=>a.sortIndex-b.sortIndex),[topics]);
 const resourceById=useMemo(()=>new Map(resources.map(item=>[item.id,item])),[resources]);
 const institutionById=useMemo(()=>new Map(institutions.map(item=>[item.id,item])),[institutions]);
 const [surface,setSurface]=useState<Surface>("index"),[lens,setLens]=useState<Lens>("story"),[inquiryId,setInquiryId]=useState(atlasInquiries[0].id),[stepIndex,setStepIndex]=useState(0),[evidenceId,setEvidenceId]=useState<string|null>(null);
 const inquiry=atlasInquiries.find(item=>item.id===inquiryId)??atlasInquiries[0],topic=sortedTopics[inquiry.topicIndex]??sortedTopics[0];
 const topicResources=useMemo(()=>resources.filter(item=>item.primaryTopicId===topic?.id||item.topicIds.includes(topic?.id)),[resources,topic]);
 const curatedStory=curatedStories.find(item=>item.id===inquiry.storyId);
 const fallbackSteps=topicResources.slice().sort((a,b)=>dateOf(a).localeCompare(dateOf(b))).slice(0,5).map((item,index)=>({chapterNo:index+1,textZh:item.summaryZh||item.summaryShort||item.titleZh,evidenceIds:[item.id]}));
 const steps=curatedStory?.steps.length?curatedStory.steps:fallbackSteps,activeStep=steps[Math.min(stepIndex,Math.max(steps.length-1,0))];
 const pathResources=Array.from(new Set(steps.flatMap(item=>item.evidenceIds))).map(id=>resourceById.get(id)).filter(Boolean) as Resource[];
 const activeEvidence=evidenceId?resourceById.get(evidenceId):activeStep?.evidenceIds.map(id=>resourceById.get(id)).find(Boolean);
 const comparison=sortedTopics.map(item=>buildComparison(item,resources)),activeComparison=comparison.find(item=>item.topic.id===topic?.id)??comparison[0];
 const move=(event:ReactPointerEvent<HTMLElement>)=>{const box=event.currentTarget.getBoundingClientRect();event.currentTarget.style.setProperty("--atlas-x",`${event.clientX-box.left}px`);event.currentTarget.style.setProperty("--atlas-y",`${event.clientY-box.top}px`)};
 const openInquiry=(id:string)=>{setInquiryId(id);setStepIndex(0);setEvidenceId(null);setLens("story");setSurface("journey")};
 return <main className="atlas-room" onPointerMove={move}>
  <Image src="/image/topic-workbench-cg-v2.png" alt="档案知识阅读工作台" fill priority sizes="100vw" className="atlas-room__background"/><div className="atlas-room__grade"/><div className="atlas-room__lamp"/>
  <Link href="/stacks?country=usa" className="atlas-room__back">返回档案架</Link><header className="atlas-room__heading"><span>ARCHIVAL KNOWLEDGE ATLAS</span><h1>美国档案知识脉络</h1><p>从一个研究问题出发，沿故事、证据与机构关系查阅真实资料</p></header>
  {surface==="index"&&<section className="atlas-index" aria-label="六个研究问题"><div className="atlas-index__desk"><span>研究问题索引</span><h2>你想从哪条线索开始？</h2><p>六份待查档案对应六个知识主题。打开一份，进入它的时间叙事与证据关系。</p><button onClick={()=>setSurface("compare")}>展开六专题对照</button></div><div className="atlas-index__folders">{atlasInquiries.map((item,index)=><button key={item.id} onClick={()=>openInquiry(item.id)} style={{"--atlas-order":index} as React.CSSProperties}><i>{String(index+1).padStart(2,"0")}</i><span>{item.title}</span><strong>{item.question}</strong><small>{item.brief}</small><b>抽取档案</b></button>)}</div></section>}
  {surface==="journey"&&<section className="atlas-journey"><nav className="atlas-journey__rail"><button onClick={()=>setSurface("index")}>六条路径</button><span>{topic?.titleZh}</span><button className={lens==="story"?"is-active":""} onClick={()=>setLens("story")}>故事脉络</button><button className={lens==="relations"?"is-active":""} onClick={()=>setLens("relations")}>关系证据</button><button onClick={()=>setSurface("compare")}>专题对照</button></nav>
   {lens==="story"?<div className="atlas-folio"><div className="atlas-folio__tabs">{steps.map((step,index)=><button key={index} className={index===stepIndex?"is-active":""} onClick={()=>{setStepIndex(index);setEvidenceId(null)}}><i>{String(index+1).padStart(2,"0")}</i><span>{step.evidenceIds.map(id=>dateOf(resourceById.get(id))).find(Boolean)||"线索"}</span></button>)}</div><article key={`${inquiryId}-${stepIndex}`} className="atlas-folio__paper"><span className="atlas-folio__kicker">{curatedStory?"人工编排故事":"按资料时间编排"} · {stepIndex+1}/{steps.length}</span><h2>{curatedStory?.titleZh??inquiry.title}</h2><p className="atlas-folio__question">{inquiry.question}</p><p className="atlas-folio__story">{activeStep?.textZh||"该专题的资料正在整理。"}</p><div className="atlas-folio__evidence"><span>本页证据</span>{activeStep?.evidenceIds.map(id=>{const item=resourceById.get(id);return item?<button key={id} onClick={()=>setEvidenceId(id)}><b>{resourceTypeZh[item.resourceType]}</b>{item.titleZh||item.titleEn}</button>:null})}</div><footer><button disabled={stepIndex===0} onClick={()=>setStepIndex(value=>value-1)}>上一页</button><span>{topicResources.length} 条专题资料可继续查阅</span><button disabled={stepIndex>=steps.length-1} onClick={()=>setStepIndex(value=>value+1)}>下一页</button></footer></article><EvidenceSlip resource={activeEvidence} institution={activeEvidence?institutionById.get(activeEvidence.institutionId):undefined}/></div>
   :<div className="atlas-chain"><header><span>关系证据链</span><h2>{inquiry.question}</h2><p>实线表示资料中已记录或人工核验的关系，虚线表示用于导览的解释性关联。</p></header><div className="atlas-chain__path">{pathResources.map((item,index)=>{const next=pathResources[index+1],relation=next?resolveRelation(item.id,next.id,relations):null;return <div className="atlas-chain__unit" key={item.id}><button className={activeEvidence?.id===item.id?"is-active":""} onClick={()=>setEvidenceId(item.id)}><i>{String(index+1).padStart(2,"0")}</i><span>{resourceTypeZh[item.resourceType]} · {dateOf(item)}</span><strong>{item.titleZh||item.titleEn}</strong></button>{next&&<div className={`atlas-chain__link ${relation?.verified?"is-verified":""}`}><span>{relation?.label||"解释性关联"}</span><small>{relation?.verified?"已人工核验":"待进一步核验"}</small></div>}</div>})}</div><EvidenceSlip resource={activeEvidence??pathResources[0]} institution={institutionById.get((activeEvidence??pathResources[0])?.institutionId)}/></div>}
  </section>}
  {surface==="compare"&&<section className="atlas-compare"><nav><button onClick={()=>setSurface("index")}>返回问题索引</button><span>六专题比较台</span></nav><div className="atlas-compare__spines">{comparison.map((record,index)=><button key={record.topic.id} className={record.topic.id===topic?.id?"is-active":""} onClick={()=>setInquiryId(atlasInquiries[index]?.id??atlasInquiries[0].id)}><i>{String(index+1).padStart(2,"0")}</i><strong>{record.topic.titleZh}</strong><span>{record.count} 件</span></button>)}</div>{activeComparison&&<article className="atlas-compare__sheet"><span>COMPARATIVE READING</span><h2>{activeComparison.topic.titleZh}</h2><p>{activeComparison.topic.description||activeComparison.topic.shortDescription}</p><dl><div><dt>资料规模</dt><dd>{activeComparison.count} 条</dd></div><div><dt>涉及机构</dt><dd>{activeComparison.institutions} 家</dd></div><div><dt>时间跨度</dt><dd>{activeComparison.span}</dd></div><div><dt>知识角色</dt><dd>{activeComparison.roles.length} 类</dd></div></dl><section><h3>资料构成</h3>{activeComparison.roles.map(([role,count])=><p key={role}><b>{knowledgeRoleZh[role as keyof typeof knowledgeRoleZh]}</b><span>{count} 条</span></p>)}</section><footer><button onClick={()=>openInquiry(inquiryId)}>进入这条研究路径</button><Link href={`/topics/${activeComparison.topic.slug}`}>查看专题全部资料</Link></footer></article>}</section>}
 </main>
}

function EvidenceSlip({resource,institution}:{resource?:Resource;institution?:Institution}){if(!resource)return <aside className="atlas-evidence"><span>EVIDENCE NOTE</span><h3>选择一条证据</h3><p>点击叙事中的资料或关系节点，在这里核验来源。</p></aside>;return <aside className="atlas-evidence" key={resource.id}><span>EVIDENCE NOTE</span><h3>{resource.titleZh||resource.titleEn}</h3><p>{resource.summaryShort||resource.summaryZh}</p><dl><div><dt>形成时间</dt><dd>{dateOf(resource)||"未记录"}</dd></div><div><dt>来源机构</dt><dd>{institution?.nameZh||"待核"}</dd></div><div><dt>知识角色</dt><dd>{knowledgeRoleZh[getKnowledgeRole(resource)]}</dd></div><div><dt>核验状态</dt><dd>{resource.status==="reviewed"||resource.status==="published"?"已整理":"待复核"}</dd></div></dl><Link href={`/resources/${resource.slug}`}>打开完整档案</Link></aside>}
function dateOf(resource?:Resource){return(resource?.publishDate||resource?.updatedDate||"").slice(0,4)}
function resolveRelation(source:string,target:string,relations:EntityRelation[]){const curated=curatedAuthorizationDrafts.find(item=>(item.source===source&&item.target===target)||(item.source===target&&item.target===source));if(curated)return{label:curated.type==="AUTHORIZE"?"制度依据":"修订演进",verified:curated.status==="verified"};const relation=relations.find(item=>(item.sourceId===source&&item.targetId===target)||(item.sourceId===target&&item.targetId===source));return relation?{label:relation.relationLabelZh,verified:relation.confidence==="high"}:null}
function buildComparison(topic:Topic,resources:Resource[]){const related=resources.filter(item=>item.primaryTopicId===topic.id||item.topicIds.includes(topic.id)),years=related.map(dateOf).filter(Boolean).sort(),roles=Array.from(related.reduce((map,item)=>map.set(getKnowledgeRole(item),(map.get(getKnowledgeRole(item))??0)+1),new Map<string,number>()).entries()).sort((a,b)=>b[1]-a[1]);return{topic,count:related.length,institutions:new Set(related.map(item=>item.institutionId)).size,span:years.length?`${years[0]} 至 ${years.at(-1)}`:"待整理",roles}}
