import Image from "next/image";
import Link from "next/link";
type Related={slug:string;title:string;institution:string;relation:string};
export type ReadingDossier={id:string;title:string;titleEn:string;summary:string;keyPoints:string[];researchValue:string;typeLabel:string;roleLabel:string;institutionName:string;institutionSlug?:string;topicTitle:string;topicSlug?:string;publishDate:string;updatedDate:string;sourceDomain:string;linkStatus:string;snapshotStatus:string;sourceUrl?:string;snapshotHref?:string;snapshotPreview?:string;officialHref?:string;officialLabel?:string;tags:string[];versions:number;files:number;related:Related[]};
const tabs=[["summary","快速理解","01"],["points","内容要点","02"],["source","来源凭证","03"],["leads","研究线索","04"]] as const;
export function ResourceReadingDesk({dossier}:{dossier:ReadingDossier}){
 const points=dossier.keyPoints.slice(0,5);
 return <main className="reading-desk reading-desk--spread">
  <Image src="/image/topic-workbench-cg-v2.png" alt="第一视角档案查阅桌面" fill priority sizes="100vw" className="reading-desk__background"/><div className="reading-desk__grade"/><Link className="reading-desk__back" href={dossier.topicSlug?`/topics/${dossier.topicSlug}`:"/resources"}>← 合上档案并返回专题</Link>
  <header className="reading-desk__heading"><span>OPEN RECORD · {dossier.id}</span><h1>{dossier.title}</h1><p>已从“{dossier.topicTitle}”专题卷宗中调取</p></header>
  {tabs.map(([id],index)=><input key={id} className="reading-desk__switch" type="radio" name="record-section" id={`record-${id}`} defaultChecked={index===0}/>) }
  {dossier.snapshotPreview&&dossier.snapshotHref?<input className="reading-snapshot__toggle" type="checkbox" id="snapshot-enlarge"/>:null}
  <nav className="reading-desk__tabs" aria-label="档案内容分卷">{tabs.map(([id,label,index])=><label key={id} htmlFor={`record-${id}`}><i>{index}</i><strong>{label}</strong></label>)}</nav>
  <article className="reading-file reading-file--spread"><div className="reading-file__cover"/><div className="reading-spread">
   <section className="reading-spread__panel reading-spread__panel--summary"><div className="reading-page reading-page--left"><span className="reading-file__kicker">RECORD IDENTITY</span><h2>资料身份卡</h2><div className="reading-identity"><div className="reading-identity__mark"><b>{dossier.typeLabel}</b><span>{dossier.roleLabel}</span></div><dl><div><dt>发布机构</dt><dd>{dossier.institutionName}</dd></div><div><dt>所属专题</dt><dd>{dossier.topicTitle}</dd></div><div><dt>发布日期</dt><dd>{dossier.publishDate||"未记录"}</dd></div><div><dt>来源状态</dt><dd>{dossier.linkStatus}</dd></div></dl></div><div className="reading-page__index"><span>INDEX TERMS</span>{dossier.tags.slice(0,5).map(tag=><b key={tag}>{tag}</b>)}</div><small className="reading-page__number">01</small></div>
    <div className="reading-page reading-page--right"><span className="reading-file__kicker">READING BRIEF</span><h2>快速理解</h2><p className="reading-file__lead">{dossier.summary}</p><div className="reading-brief"><span>建议关注</span>{points.slice(0,3).map((point,index)=><p key={index}><b>{String(index+1).padStart(2,"0")}</b>{point}</p>)}</div><blockquote>这份资料可以帮助理解“{dossier.topicTitle}”中制度、机构与实践之间的联系。</blockquote><small className="reading-page__number">02</small></div></section>
   <section className="reading-spread__panel reading-spread__panel--points"><div className="reading-page reading-page--left"><span className="reading-file__kicker">KEY FINDINGS · I</span><h2>核心内容</h2><ol className="reading-file__points">{points.slice(0,3).map((point,index)=><li key={index}><b>{String(index+1).padStart(2,"0")}</b><p>{point}</p></li>)}</ol><small className="reading-page__number">03</small></div><div className="reading-page reading-page--right"><span className="reading-file__kicker">KEY FINDINGS · II</span><h2>继续阅读</h2><ol className="reading-file__points">{points.slice(3).map((point,index)=><li key={index}><b>{String(index+4).padStart(2,"0")}</b><p>{point}</p></li>)}</ol><div className="reading-margin-note"><span>研究提示</span><p>{dossier.researchValue}</p></div><small className="reading-page__number">04</small></div></section>
   <section className="reading-spread__panel reading-spread__panel--source"><div className="reading-page reading-page--left"><span className="reading-file__kicker">PROVENANCE & PRESERVATION</span><h2>来源与保存</h2><dl className="reading-source-ledger"><div><dt>来源域名</dt><dd>{dossier.sourceDomain||"未记录"}</dd></div><div><dt>发布日期</dt><dd>{dossier.publishDate||"未记录"}</dd></div><div><dt>更新日期</dt><dd>{dossier.updatedDate||"未记录"}</dd></div><div><dt>链接状态</dt><dd>{dossier.linkStatus}</dd></div></dl><div className="reading-preservation-counts"><span><strong>{dossier.files}</strong>份来源文件</span><span><strong>{dossier.versions}</strong>个版本节点</span><span><strong>{dossier.snapshotStatus}</strong>快照状态</span></div><p className="reading-file__note">本站保存件用于来源核验与学术研究；正式引用时，请优先核对发布机构的当前有效文本。</p><small className="reading-page__number">05</small></div><div className="reading-page reading-page--right"><span className="reading-file__kicker">ARCHIVE SNAPSHOT</span><h2>档案快照</h2>{dossier.snapshotPreview&&dossier.snapshotHref?<label className="reading-snapshot" htmlFor="snapshot-enlarge"><img src={dossier.snapshotPreview} alt={`${dossier.title} 的站内档案快照`}/><span>点击放大查阅快照</span></label>:<div className="reading-snapshot reading-snapshot--empty"><div><b>暂无影像</b><span>暂未捕捉到快照</span></div></div>}<div className="reading-source-actions">{dossier.snapshotHref?<a href={dossier.snapshotHref} target="_blank" rel="noopener noreferrer">打开原始快照</a>:null}{dossier.snapshotHref?<a href={dossier.snapshotHref} download>保存快照 ↓</a>:null}{dossier.officialHref?<a href={dossier.officialHref} target="_blank" rel="noopener noreferrer">{dossier.officialLabel||"查看官方文本"}</a>:null}{dossier.sourceUrl?<a className="is-primary" href={dossier.sourceUrl} target="_blank" rel="noopener noreferrer">官方来源 ↗</a>:null}</div><small className="reading-page__number">06</small></div></section>
   <section className="reading-spread__panel reading-spread__panel--leads"><div className="reading-page reading-page--left"><span className="reading-file__kicker">RESEARCH VALUE</span><h2>研究价值</h2><p className="reading-file__value">{dossier.researchValue}</p><div className="reading-page__index"><span>RESEARCH TERMS</span>{dossier.tags.slice(0,6).map(tag=><b key={tag}>{tag}</b>)}</div><small className="reading-page__number">07</small></div><div className="reading-page reading-page--right"><span className="reading-file__kicker">FOLLOW THE TRAIL</span><h2>强关联资料</h2>{dossier.related.length?<div className="reading-file__related reading-file__related--explained">{dossier.related.slice(0,4).map((item,index)=><Link key={item.slug} href={`/resources/${item.slug}`}><b>{String(index+1).padStart(2,"0")}</b><span>{item.title}<small>{item.relation}</small><small>{item.institution}</small></span><em>调取 →</em></Link>)}</div>:<p className="reading-margin-note">暂未建立明确关联资料。</p>}<small className="reading-page__number">08</small></div></section>
  </div></article>{dossier.snapshotPreview&&dossier.snapshotHref?<section className="snapshot-viewer" aria-label="档案快照放大查看"><label className="snapshot-viewer__shade" htmlFor="snapshot-enlarge" aria-label="关闭快照"/><div className="snapshot-viewer__stage"><header><div><span>ARCHIVE SNAPSHOT</span><strong>{dossier.title}</strong></div><div><a href={dossier.snapshotHref} download>保存影像 ↓</a><a href={dossier.snapshotHref} target="_blank" rel="noopener noreferrer">打开原文件 ↗</a><label htmlFor="snapshot-enlarge">关闭 ×</label></div></header><div className="snapshot-viewer__image"><img src={dossier.snapshotPreview} alt={`${dossier.title} 的放大档案快照`}/></div></div></section>:null}<div className="reading-desk__hint">选择左侧分卷签 · 翻阅这份档案</div>
 </main>;
}
