"use client";
import Image from "next/image";
import Link from "next/link";
import type { Country, Institution, Resource, Topic } from "@/types";
import type { PointerEvent as ReactPointerEvent } from "react";
import { resourceTypeZh } from "@/lib/display";

type Props={country:Country;institutions:Institution[];resources:Resource[];topics:Topic[]};
const groupLabels:Record<string,string>={federal:"联邦机构",state:"各州机构",social:"社会机构",academic:"高校与研究机构",commercial:"商业与服务机构",other:"其他机构"};
const views=[{id:"overview",label:"国家总览",en:"COUNTRY FILE"},{id:"topics",label:"研究专题",en:"TOPIC INDEX"},{id:"institutions",label:"机构体系",en:"AUTHORITY FILE"},{id:"preservation",label:"保存状态",en:"PRESERVATION"}];
export function UsaCountryDossier({country,institutions,resources,topics}:Props){
 const backed=resources.filter(r=>r.hasBackup),healthy=resources.filter(r=>r.linkStatus==="ok");
 const move=(e:ReactPointerEvent<HTMLElement>)=>{const b=e.currentTarget.getBoundingClientRect();e.currentTarget.style.setProperty("--country-x",`${e.clientX-b.left}px`);e.currentTarget.style.setProperty("--country-y",`${e.clientY-b.top}px`)};
 return <main className="country-room" onPointerMove={move}><Image src="/image/institution-fonds-desk-v2.png" alt="国家档案导览工作台" fill priority sizes="100vw" className="country-room__background"/><div className="country-room__grade"/><div className="country-room__focus"/>
  <Link className="country-room__back" href="/countries">← 返回国家地区</Link><header className="country-room__heading"><span>{country.iso3} · NATIONAL ARCHIVAL GUIDE</span><h1>{country.nameZh}档案资料总卷</h1><p>{country.descriptionZh}</p></header>
  <aside className="country-room__index"><span>总卷索引</span>{views.map((v,i)=><a key={v.id} href={`#country-${v.id}`}><i>{String(i+1).padStart(2,"0")}</i><b>{v.label}</b><small>{v.en}</small></a>)}</aside>
  <section className="country-folio"><div className="country-folio__layers"><i/><i/></div>
   <article id="country-overview" className="country-panel country-panel--overview"><Head en="COUNTRY FILE" title="国家总览" text="这不是统计终点，而是进入美国档案资料、研究问题与责任机构的总入口。"/><div className="country-overview"><div className="country-overview__intro"><span>总卷说明</span><p>{country.descriptionZh}</p><p>建议从档案资料板块进入：左侧选择研究专题，右侧选择机构类别；遇到关键资料时可继续查看来源凭证、档案快照和关联文献。</p><Link href="/stacks?country=usa">进入美国档案资料板块 →</Link></div><div className="country-overview__numbers"><span><b>{resources.length}</b>资料条目<small>法规、政策、指南、系统与项目</small></span><span><b>{institutions.length}</b>相关机构<small>联邦、州级、社会与学术机构</small></span><span><b>{topics.length}</b>研究专题<small>从研究问题组织资料</small></span><span><b>{backed.length}</b>保存副本<small>已捕捉快照或本地备份</small></span></div><div className="country-overview__path"><span>01 选择专题或机构</span><i>→</i><span>02 调阅核心资料</span><i>→</i><span>03 核对来源快照</span><i>→</i><span>04 建立研究线索</span></div></div><Foot text={`${resources.length} 条资料已进入总卷`}/></article>
   <article id="country-topics" className="country-panel country-panel--topics"><Head en="TOPIC INDEX" title="研究专题" text="六条研究问题构成美国档案资料板块的主要叙事线索。"/><div className="country-topic-list">{topics.map((t,i)=>{const count=resources.filter(r=>r.primaryTopicId===t.id||r.topicIds.includes(t.id)).length;return <Link href={`/topics/${t.slug}`} key={t.id}><i>{String(i+1).padStart(2,"0")}</i><div><span>{count} 条关联资料</span><h3>{t.titleZh}</h3><p>{t.plainQuestion}</p></div><b>进入专题 →</b></Link>})}</div><Foot text={`${topics.length} 条研究路径`}/></article>
   <article id="country-institutions" className="country-panel country-panel--institutions"><Head en="AUTHORITY FILE" title="机构体系" text="按机构类别进入目录柜，再从全宗登记卡追踪职责、馆藏与代表资料。"/><div className="country-group-list">{Object.entries(groupLabels).map(([group,label],i)=>{const list=institutions.filter(x=>(x.institutionGroup??"other")===group),rc=resources.filter(r=>list.some(x=>x.id===r.institutionId)).length;return <Link href={`/institutions/usa?group=${group}`} key={group}><i>{String(i+1).padStart(2,"0")}</i><div><span>{list.length} 个机构 · {rc} 条资料</span><h3>{label}</h3><p>{list.slice(0,3).map(x=>x.shortName||x.nameZh).join(" · ")||"目录正在建设"}</p></div><b>打开目录柜 →</b></Link>})}</div><Foot text={`${institutions.length} 个机构全宗入口`}/></article>
   <article id="country-preservation" className="country-panel country-panel--preservation"><Head en="PRESERVATION REGISTER" title="保存与核验" text="用链接状态、快照覆盖和最近核验信息判断资料能否持续访问与正式引用。"/><div className="country-preservation"><div className="country-preservation__metrics"><span><b>{healthy.length}</b>链接正常<small>{Math.round(healthy.length/Math.max(1,resources.length)*100)}% 当前可访问</small></span><span><b>{backed.length}</b>已有备份<small>{Math.round(backed.length/Math.max(1,resources.length)*100)}% 保存覆盖</small></span><span><b>{resources.length-backed.length}</b>待补快照<small>优先处理关键法规与政策</small></span></div><div className="country-preservation__records">{backed.slice(0,6).map((r,i)=><Link href={`/resources/${r.slug}`} key={r.id}><i>{String(i+1).padStart(2,"0")}</i><div><span>{resourceTypeZh[r.resourceType]} · {r.lastCheckedAt||"待核验"}</span><h3>{r.titleZh||r.titleEn}</h3></div><b>查看凭证 →</b></Link>)}</div><Link className="country-preservation__all" href="/resources?country=usa">进入完整资料目录 →</Link></div><Foot text={`${backed.length} 条资料已有保存副本`}/></article>
  </section>
 </main>}
function Head({en,title,text}:{en:string;title:string;text:string}){return <header className="country-panel__head"><div><span>{en}</span><h2>{title}</h2></div><p>{text}</p></header>}
function Foot({text}:{text:string}){return <footer className="country-panel__foot"><span>ARCHIVESCOPE · USA DOSSIER</span><b>{text}</b></footer>}
